name: APK Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install aiohttp beautifulsoup4

      - name: Run main script
        run: python main.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Pull latest changes
        run: git pull origin main

      - name: Add and Commit changes
        run: |
          # فقط فایل‌های موجود را اضافه کنید
          for file in packages.json progress.json updated_packages.html; do
            if [ -f "$file" ]; then
              git add "$file"
            fi
          done

          # اگر تغییری برای commit وجود دارد
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automated update: $(date +'%Y-%m-%d %H:%M')"
          else
            echo "No changes to commit"
          fi

      - name: Push changes
        run: git push origin main
