name: APK Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install aiohttp beautifulsoup4

      - name: Run main script
        run: python main.py

- name: Commit changes
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "actions@github.com"
    ls -l packages.json progress.json updated_packages.html || true
    if [ -f packages.json ]; then git add packages.json; fi
    if [ -f progress.json ]; then git add progress.json; fi
    if [ -f updated_packages.html ]; then git add updated_packages.html; fi
    git diff --cached --quiet || git commit -m "Update package versions"
    git pull --rebase origin main || true
    git push origin main

